#!/bin/bash
# Build script for frontend — generates env-config.js with runtime environment variables.
# This script is called by Vercel during deployment.

echo "Building frontend..."

if [ -n "$BACKEND_API_URL" ]; then
    echo "Generating env-config.js with BACKEND_API_URL: $BACKEND_API_URL"
    cat > js/env-config.js << EOF
// Auto-generated by build.sh — do not edit manually
window.__ENV__ = {
    API_BASE_URL: "${BACKEND_API_URL}"
};
EOF
else
    echo "Warning: BACKEND_API_URL is not set. Using default production URL."
    cat > js/env-config.js << EOF
// Auto-generated by build.sh — BACKEND_API_URL was not set
window.__ENV__ = {
    API_BASE_URL: "https://suraksha-scan.onrender.com"
};
EOF
fi

echo "Frontend build complete."
